# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

pod 'Cards'

target 'Teachify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Teachify

  target 'TeachifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeachifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
